### ISSUE TITLE
Groovy 2.4.6 and this plugin 2.3.0 reports not the correct code coverage

### ISSUE THREAD

**Issue by smily75** [stevesaliman/gradle-cobertura-plugin#105]
Hello,
we have a problem with cobertura coverage results. When executing our tests using IntelliJ IDEA the coverage analysis tells us, that we have 100% code coverage, but when executing the same tests using the cobertura gradle plugin, the coverage results of some classes are really strange: some methods seem to not been tested at all and some methods have a coverage that is partially or totally wrong (e.g. 25% coverage). This seems to be a result of groovy code optimization, but we need a solution. Do You have an idea?
Best regards,
Sandra

**Comment by stevesaliman** [comment]
Unfortunately, I don't have any good ideas as to what might be going wrong.

You mentioned groovy optimizations - are the classes with the bad coverage numbers groovy classes?  Others have reported issues with Cobertura and Groovy.

Also, It's a pretty good bet that Intellij is using a different tool to generate its coverage metrics.  I wouldn't be too surprised if Intellij's tool was better at getting accurate reports than Cobertura.

Sorry I couldn't be more help,

Steve

**Comment by smily75** [comment]
Yes, we have only groovy classes. Why the cobertura can't correctly analysed groovy code?
Since groovy is not a language used by only a few developers, we think, it is not understandable, that groovy is so stepmotherly supported by cobertura.

**Comment by stevesaliman** [comment]
I agree that it would be nice for Cobertura to be kept more up to date.  It has been a year since the last Cobertura release.

The Cobertura plugin is meant to be a simple wrapper around the core Cobertura functionality, which means that unless there is some kind of classpath problem introduced by the plugin, the problem is most likely with Cobertura itself.  You might want to report this issue there.

I've been watching the Cobertra repository, and will update to the latest version of Cobertura when it gets released. Hopefully it will help with this issue (and several others).
