### ISSUE TITLE
cobertura task always tells me it is UP-TO-DATE

### ISSUE THREAD

**Issue by Frank667** [stevesaliman/gradle-cobertura-plugin#148]
Hi,

when running `gradlew cobertura` in my android project I always get the following two lines in my log and no tests are run and no report is generated (even in a fresh workspace where no output exists):

`:app:coberturaReport UP-TO-DATE
:app:cobertura UP-TO-DATE`

My gradle-wrapper.properties point to gradle 4.1:
`distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip`

The version of the gradle-cobertura-plugin is 2.5.3.

BTW `gradlew test `runs fine.

Is there any possibility to get more information from the plugin to find out why it thinks nothing has changed?

**Comment by stevesaliman** [comment]
Unfortunately, I've never done Android development, so I'm having to make some guesses here, but I may have found a code issue.

A fix was submitted for Issue #101 that was causing problems with Android projects.  That fix was designed to skip the code that fixes the classpath of tests for Android projects under certain conditions, but the fix was skipping all the work the plugin does when it detects the `cobertura` task in the execution graph, including the code that enables the tasks that do the actual work of the plugin.

I've made a patch to the plugin, but I don't have any good way to test it at the moment.  Can you try the following, and let me know if it fixes your issue?

1. Clone this project to your machine.

2. Run `gradlew install`

3. Make your project dependent on version `2.5.4-SNAPSHOT` of the plugin

4. run `gradlew cobertura` in your project.

It's probably also worth making sure `gradlew test` still runs without generating coverage reports.

**Comment by Frank667** [comment]
Sorry, same result. `gradlew tes`t runs without generating coverage reports, `gradlew cobertura` does not run any tests, instead it tells me it's up-to-date.
Can you tell me which part of the code the issue is? Perhaps I can look into this myself if I find the time.

**Comment by stevesaliman** [comment]
That is good news.  Is there something I should add to the usage page with respect to setting the androidVariant?

I'll try to push a release this evening.  If I can't get to it tonight, I'll do a release over the weekend.

**Comment by stevesaliman** [comment]
Version 2.5.4 of the plugin has just been released, and should be available in the usual places shortly.
