### ISSUE TITLE
ClassNotFoundException on 2.2.7 but 2.2.6

### ISSUE THREAD

**Issue by nwoedf** [stevesaliman/gradle-cobertura-plugin#75]
The following is my build.gradle. As suggested by maddingo in #56, I force the ASM version to 5.0.3 for Java 8.

    plugins {
        id 'java'
        id 'eclipse'
        id 'net.saliman.cobertura' version '2.2.7'
    }

    configurations.all {
        resolutionStrategy {
            // Cobertura includes an ASM version that can't handle Java 8, ASM 5.0.3 handles Java8
            force 'org.ow2.asm:asm:5.0.3'
            forcedModules = [ 'org.ow2.asm:asm:5.0.3' ]
        }
    }

    dependencies {
        compile group: 'commons-collections', name: 'commons-collections', version: '3.2'
        testCompile group: 'junit', name: 'junit', version: '4.+'
    }

    repositories {
        mavenCentral()
    }

    cobertura.coverageFormats = ['html', 'xml']

If the version is 2.2.7, I will get the following exception

    org.nwoedf.ClassForTestingTest > test FAILED
        java.lang.NoClassDefFoundError at ClassForTestingTest.java:14
            Caused by: java.lang.ClassNotFoundException at ClassForTestingTest.java:14

But it is fine when the version is 2.2.6

**Comment by stevesaliman** [comment]
Version 2.2.7 of the plugin uses Cobertura 2.1.1 by default, which in turn, uses ASM 5.0.1.  So far, I haven't noticed any issues with JDK 1.0.0_25.  What happens if you remove the ASM 5.0.3 bits from your build.gradle?  Also, can you confirm that you aren't overriding the version of Cobertura in your ```cobertura``` block?

**Comment by nwoedf** [comment]
If build.gradle is like the following:

    plugins {
        id 'java'
        id 'eclipse'
        id 'net.saliman.cobertura' version '2.2.7'
    }

    dependencies {
        compile group: 'commons-collections', name: 'commons-collections', version: '3.2'
        testCompile group: 'junit', name: 'junit', version: '4.+'
    }

    repositories {
        mavenCentral()
    }

    cobertura.coverageFormats = ['html', 'xml']

I will get the same exception

	$ gradle clean cobertura
	:clean UP-TO-DATE
	:coberturaReport UP-TO-DATE
	:compileJava
	:processResources UP-TO-DATE
	:classes
	:instrument
	Cobertura 2.1.1 - GNU GPL License (NO WARRANTY) - See COPYRIGHT file
	:copyCoberturaDatafile
	:compileTestJava
	:processTestResources UP-TO-DATE
	:testClasses
	:test

	org.nwoedf.ClassForTestingTest > test FAILED
	    java.lang.NoClassDefFoundError at ClassForTestingTest.java:14
	        Caused by: java.lang.ClassNotFoundException at ClassForTestingTest.java:14

	1 test completed, 1 failed
	:test FAILED
	:generateCoberturaReport
	Cobertura 2.1.1 - GNU GPL License (NO WARRANTY) - See COPYRIGHT file
	Report time: 73ms
	Cobertura 2.1.1 - GNU GPL License (NO WARRANTY) - See COPYRIGHT file
	Report time: 50ms
	:performCoverageCheck SKIPPED

	FAILURE: Build failed with an exception.


Versions

    Gradle:       2.2.1
    Groovy:       2.3.6
    Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
    JVM:          1.8.0_25 (Oracle Corporation 25.25-b02)
    OS:           Mac OS X 10.10.2 x86_64

**Comment by stevesaliman** [comment]
I may have run into the same issue researching a fix to a different issue.  I'm betting that your test report in ```build/reports/test``` shows a problem with slf4j.

One of the main differences between 2.2.6 and 2.2.7 is the change in Cobertura versions from 2.0.3 to 2.1.1.  It looks like Cobertura 2.1.1 now uses the slf4j API do do its logging.  It declares a dependency on the slf4j-api, but if there is no runtime implementation of the API in your classpath, you get NoClassDefFoundError.  Cobertura doesn't declare any dependencies to an slf4j runtime because it doesn't want to assume anything about which implementation you want to use.

What happens if you add ```testRuntime "org.slf4j:slf4j-log4j12:1.7.5"``` and ```testRuntime "log4j:log4j:1.2.17"``` to your build.gradle?  Does that make the problem go away?

**Comment by thecodesmith** [comment]
I had this same issue, and your last suggestion resolved it for me. I added

    testRuntime "org.slf4j:slf4j-log4j12:1.7.5"
    testRuntime "log4j:log4j:1.2.7"

to `build.gradle` and it works like a charm. Thanks for all your work on this plugin!

**Comment by bric3** [comment]
For reference only, I used the nop logger : 

```
testRuntime 'org.slf4j:slf4j-nop:1.7.12' // for cobertura
```
