### ISSUE TITLE
Cobertura fails with Android applications

### ISSUE THREAD

**Issue by davidmichaelkarr** [stevesaliman/gradle-cobertura-plugin#82]
I'm not the person who had this problem, but I think it would be worth determining whether this can be fixed.  The following thread describes the issue:
https://discuss.gradle.org/t/use-cobertura-with-android-plugin/10231 .

**Comment by stevesaliman** [comment]
Thanks for the bug report.  

At the moment, I'm not sure how to proceed.  The Cobertura plugin was written with java classes in mind.  It assumes that there will be a ```test``` task to attach to, and that the compiled source can be found in the ```sourceSets.main.output``` property.  Without the Java plugin, these things don't appear to be present.

**Comment by davidmichaelkarr** [comment]
Yeah, I understand it might be awkward.  However, you will have Java classes, just not managed by the Java plugin.  The Android plugin might have similar constructs, just arranged differently.  It would be unfortunate if Android applications built with Maven can use Cobertura, but not if built with Gradle.

**Comment by stevesaliman** [comment]
I agree that support for Android projects is desirable.  To make this happen the plugin will need to know where to find things, and what tasks to augment, and I'm hampered by the fact that I've never done Android development.

I'm also concerned that although Android projects use Java, the android plugin explicitly prevents using the Java plugin, preferring its own way of organizing things.  The plugin won't know at apply time what other plugins will be applied, so I'd need to figure out how to make all of the configuration happen at execution time when I can determine which plugins are actually present, then I'd need to figure out where things are accordingly.

All of this makes me start to wonder if this plugin, which was written to compliment the Java, Groovy, and Scala plugins, is the right tool for generating coverage reports for Android projects.  There is a similar situation with the Liquibase plugin in a Grails project.  Grails users don't use the Liquibase plugin because Grails has its own database update mechanism that knows how a Grails project is setup.

I guess the bottom line is that if it is easy, I'd love to support Android projects because it means that the Gradle community can use one plugin for all of their Cobertura needs, like the Maven folks do.  The main difference is that the Maven plugin is probably file based instead of property based, it is more tightly bound to convention, and instead of tasks, it has well defined phases that all things must use.  Gradle works differently, and I have to add a lot of complexity to the plugin to support Androind, then perhaps a better solution would be an Android specific Cobertura plugin.
