### ISSUE TITLE
Tests failing when using cobertura and slf4j not in the build path

### ISSUE THREAD

**Issue by robyf** [stevesaliman/gradle-cobertura-plugin#98]
Hello,

I'm not sure is this a plugin problem or a cobertura problem, but I start from here. I'm trying of using this plugin, version 2.3.0, for a build done using gradle 2.10 and java 1.8.0_72 on linux amd64.

Without the plugin the unit tests (run with jUnit) work fine, when the plugin is enabled all the tests fail with NoClassDefFoundError. In order to have the tests working I had to add slf4j as compile dependency. The attached zip contains a (very simple) test app that replicates the issue: the test works without cobertura, fails with it and works again when this is added to the dependencies:

    compile 'org.slf4j:slf4j-api:1.7.13'

Could this be fixed?

Thanks in advance!
-Roberto

[test-gradle-cobertura.zip](https://github.com/stevesaliman/gradle-cobertura-plugin/files/111187/test-gradle-cobertura.zip)

**Comment by stevesaliman** [comment]
You're on the right track as far as find a solution, but you don't need to make your whole project depend on slf4j, you only need it when you're running tests.  You can change your ```compile``` dependency to a ```testRuntime``` dependency.

The reason why this is needed is a bit confusing, but I'll try to explain it as best as I can.

Gradle itself uses slf4j, and when it runs the ```instrument``` task it uses a classpath that gets jars from the project classpath, but it also gets jars from Gradle's own lib directory.  When a project is using slf4j, Cobertura complains because there is more than one slf4j-api jar file on the classpath.

To solve this problem, I have to explicitly exclude the api from the project dependencies when the Cobertura plugin is applied so that we only had one version of it in the classpath during instrumentation.  This isn't a problem for projects that use slf4j because the slf4j implementation class is still part of the project dependencies, but for projects like yours that don't use slf4j, it leaves us without any slf4j api available during unit tests, where we only have what is in the project dependencies.  The quick solution is to force it back into the classpath with a ```testRuntime``` dependency.

I should probably add this to the documentation...

**Comment by stevesaliman** [comment]
I've added the slf4j requirement to the documentation, so I think this can be closed.
